-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.all_crime
(
    event_unique_id text COLLATE pg_catalog."default" NOT NULL,
    crime text COLLATE pg_catalog."default",
    occ_year bigint,
    occ_month text COLLATE pg_catalog."default",
    occ_day bigint,
    occ_dow text COLLATE pg_catalog."default",
    occ_hour bigint,
    premises_type text COLLATE pg_catalog."default",
    hood_140 text COLLATE pg_catalog."default",
    neighbourhood_140 text COLLATE pg_catalog."default",
    long_wgs84 double precision,
    lat_wgs84 double precision,
    date text COLLATE pg_catalog."default",
    CONSTRAINT pk_event_unique_id PRIMARY KEY (event_unique_id)
);

CREATE TABLE IF NOT EXISTS public.joined_data
(
    date text COLLATE pg_catalog."default",
    max_temperature double precision,
    min_temperature double precision,
    max_relative_humidity bigint,
    avg_relative_humidity double precision,
    avg_pressure_sea double precision,
    max_wind_speed bigint,
    precipitation double precision,
    rain double precision,
    snow double precision,
    snow_on_ground double precision,
    daylight double precision,
    avg_cloud_cover_8 double precision,
    event_unique_id text COLLATE pg_catalog."default",
    crime text COLLATE pg_catalog."default",
    occ_year bigint,
    occ_month text COLLATE pg_catalog."default",
    occ_day bigint,
    occ_dow text COLLATE pg_catalog."default",
    occ_hour bigint,
    premises_type text COLLATE pg_catalog."default",
    hood_140 text COLLATE pg_catalog."default",
    neighbourhood_140 text COLLATE pg_catalog."default",
    long_wgs84 double precision,
    lat_wgs84 double precision
);

CREATE TABLE IF NOT EXISTS public.weather
(
    date text COLLATE pg_catalog."default" NOT NULL,
    max_temperature double precision,
    min_temperature double precision,
    max_relative_humidity bigint,
    avg_relative_humidity double precision,
    avg_pressure_sea double precision,
    max_wind_speed bigint,
    precipitation double precision,
    rain double precision,
    snow double precision,
    snow_on_ground double precision,
    daylight double precision,
    avg_cloud_cover_8 double precision,
    CONSTRAINT pk_weather_date PRIMARY KEY (date)
);

ALTER TABLE IF EXISTS public.all_crime
    ADD CONSTRAINT fk_date FOREIGN KEY (date)
    REFERENCES public.weather (date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;